# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: "SECRET_KEY"
  gmail_username: "gmail_user"
  gmail_password: "gmail_password"
  airbrake_api_key: "airbrake_api_key"

test:
  secret_key_base: "GENERATE A KEY FOR THIS ONE"

staging:
  secret_key_base: "SECRET TOKEN"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["secret_token"] %>

